name: Application CI

on:
  push:
    branches: [ main ]

jobs:
  node_build:
    uses: thejitenderk/reusable-workflow/.github/workflows/practice.yml@main
    with:
      node_version: "16"
      build_command: "npm run build"
      artifact_path: "build"
